# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kendra Dunsmoor
title: Software Engineer
email: kendradunsmoor@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  kendra-dunsmoor
linkedin_username: kendra-dunsmoor

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kendra Dunsmoor. I'm currently a Software Development Engineer II at Amazon who enjoys creating games on the side!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Ice Cream Scream
        link: https://kendra-dunsmoor.github.io/IceCreamScream
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
          A 2D action game created using Unity engine and C# where you play as a small penguin trying to escape from attacking ice cream monsters!
  #- title: Experience # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Amazon
  #      link: 
  #      # link_text: 
  #      sub_title: Title
  #      caption: August 2021 - Present
  #      quote: >
  #        quote
  #      description: | # this will include new lines to allow paragraphs
  #          description

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stanford University
        caption: 2017 - 2021
        sub_title: B.S. in Computer Science, Artificial Intelligence track

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming some of my other hobbies are:
      - Volleyball
      - Painting
      - Baking
      - Gaming

 #     Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
